# Generated by Django 6.0.4 on 2026-04-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='appointment_time',
            field=models.DateField(auto_now=True),
        ),
    ]
